import{a as M,S as q,i as a}from"./assets/vendor-BSTwZ_tR.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const P="https://pixabay.com/api/",R="52318112-aedb8ccc797c66be623deef69",f=15;async function m(o,r){const n={key:R,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:f};try{return(await M.get(P,{params:n})).data}catch(s){throw s}}const u=document.querySelector(".gallery"),y=document.querySelector(".loader"),h=document.querySelector(".load-more-btn"),E=new q(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function g(o){const r=o.map(({webformatURL:n,largeImageURL:s,tags:e,likes:t,views:c,comments:v,downloads:S})=>`
          <li class="gallery-item">
            <a href="${s}">
              <img src="${n}" alt="${e}" loading="lazy" />
            </a>
            <div class="info">
              <p><b>Likes:</b> ${t}</p>
              <p><b>Views:</b> ${c}</p>
              <p><b>Comments:</b> ${v}</p>
              <p><b>Downloads:</b> ${S}</p>
            </div>
          </li>
        `).join("");u.insertAdjacentHTML("beforeend",r),E.refresh()}function $(){u.innerHTML=""}function b(){y.classList.remove("hidden")}function L(){y.classList.add("hidden")}function w(){h.classList.remove("hidden")}function p(){h.classList.add("hidden")}const d=document.querySelector(".form");let i,l="";p();d.addEventListener("submit",B);async function B(o){if(o.preventDefault(),p(),i=1,l=d.elements["search-text"].value.trim(),l===""){a.show({message:"Fill in the search bar!",color:"red",position:"topRight"});return}$();try{b();const r=await m(l,i);if(r.hits.length===0){a.show({message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"});return}if(g(r.hits),d.reset(),i===Math.ceil(r.totalHits/f)){a.show({message:"We're sorry, but you've reached the end of search results.",color:"blue",position:"topRight"});return}else i++,w()}catch{a.show({message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"})}finally{L()}}h.addEventListener("click",O);async function O(){p();try{b();const o=await m(l,i);if(g(o.hits),x(),i++,i===Math.ceil(o.totalHits/15)){a.show({message:"We're sorry, but you've reached the end of search results.",color:"blue",position:"topRight"});return}else w()}catch{a.show({message:"Sorry, there are some problems...",color:"red",position:"topRight"})}finally{L()}}function x(){const{height:o}=u.firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
