import{a as w,S as v,i as a}from"./assets/vendor-BSTwZ_tR.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const S="https://pixabay.com/api/",q="52318112-aedb8ccc797c66be623deef69";async function f(r,o){const n={key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};try{return(await w.get(S,{params:n})).data}catch(s){throw s}}const d=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more-btn"),M=new v(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function p(r){d.innerHTML+=r.map(({webformatURL:o,largeImageURL:n,tags:s,likes:e,views:t,comments:c,downloads:L})=>`
          <li class="gallery-item">
            <a href="${n}">
              <img src="${o}" alt="${s}" loading="lazy" />
            </a>
            <div class="info">
              <p><b>Likes:</b> ${e}</p>
              <p><b>Views:</b> ${t}</p>
              <p><b>Comments:</b> ${c}</p>
              <p><b>Downloads:</b> ${L}</p>
            </div>
          </li>
        `).join(""),M.refresh()}function P(){d.innerHTML=""}function y(){m.classList.remove("hidden")}function g(){m.classList.add("hidden")}function b(){h.classList.remove("hidden")}function R(){h.classList.add("hidden")}function E(){const{height:r}=d.firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}const u=document.querySelector(".form");let i,l="";u.addEventListener("submit",$);async function $(r){if(r.preventDefault(),i=1,l=u.elements["search-text"].value.trim(),l===""){a.show({message:"Fill in the search bar!",color:"red",position:"topRight"});return}P(),y();try{const o=await f(l,i);if(o.hits.length===0){a.show({message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"});return}if(p(o.hits),i++,i===Math.ceil(o.totalHits/15)){a.show({message:"We're sorry, but you've reached the end of search results.",color:"blue",position:"topRight"});return}else b()}catch{a.show({message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"})}finally{g(),u.reset()}}h.addEventListener("click",B);async function B(){R(),y();try{const r=await f(l,i);if(p(r.hits),E(),i++,i===Math.ceil(r.totalHits/15)){a.show({message:"We're sorry, but you've reached the end of search results.",color:"blue",position:"topRight"});return}else b()}catch{a.show({message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"})}finally{g()}}
//# sourceMappingURL=index.js.map
