import{a as M,S as P,i as a}from"./assets/vendor-BSTwZ_tR.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const q="https://pixabay.com/api/",R="52318112-aedb8ccc797c66be623deef69",h=15;async function m(t,o){const n={key:R,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:h};try{return(await M.get(q,{params:n})).data}catch(s){throw s}}const p=document.querySelector(".gallery"),g=document.querySelector(".loader"),f=document.querySelector(".load-more-btn"),E=new P(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function y(t){if(t.length===0)return;const o=t.map(({webformatURL:n,largeImageURL:s,tags:e,likes:r,views:c,comments:v,downloads:S})=>`
          <li class="gallery-item">
            <a href="${s}">
              <img src="${n}" alt="${e}" loading="lazy" />
            </a>
            <div class="info">
              <p><b>Likes:</b> ${r}</p>
              <p><b>Views:</b> ${c}</p>
              <p><b>Comments:</b> ${v}</p>
              <p><b>Downloads:</b> ${S}</p>
            </div>
          </li>
        `).join("");p.insertAdjacentHTML("beforeend",o),E.refresh()}function $(){p.innerHTML=""}function b(){g.classList.remove("hidden")}function L(){g.classList.add("hidden")}function w(){f.classList.remove("hidden")}function l(){f.classList.add("hidden")}const u=document.querySelector(".form");let i,d="";l();u.addEventListener("submit",B);async function B(t){if(t.preventDefault(),l(),i=1,d=u.elements["search-text"].value.trim(),d===""){a.show({message:"Fill in the search bar!",color:"red",position:"topRight"});return}$();try{b();const o=await m(d,i);if(o.hits.length===0){a.show({message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"});return}if(y(o.hits),u.reset(),i===Math.ceil(o.totalHits/h)){a.show({message:"We're sorry, but you've reached the end of search results.",color:"blue",position:"topRight"}),l();return}else w();i++}catch{a.show({message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"})}finally{L()}}f.addEventListener("click",O);async function O(){l();try{b();const t=await m(d,i);y(t.hits),x(),i++;const o=Math.ceil(t.totalHits/h);i>o||t.hits.length<h?(a.show({message:"We're sorry, but you've reached the end of search results.",color:"blue",position:"topRight"}),l()):w()}catch{a.show({message:"Sorry, there are some problems...",color:"red",position:"topRight"})}finally{L()}}function x(){const{height:t}=p.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
